<a href="https://colab.research.google.com/github/d-monkey-CG/Dallas_County_ResidentialProperty_Stats/blob/main/DCAD_Transform.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [16]:
#This is the script I used to pre-process DCAD data by year to add to preliminary dataset

#file_path_appr = '/content/drive/MyDrive/Dallas_County_25YR_Data/DCAD2025_CURRENT/ACCOUNT_APPRL_YEAR.CSV'
#file_path_info = '/content/drive/MyDrive/Dallas_County_25YR_Data/DCAD2025_CURRENT/ACCOUNT_INFO.CSV'
#file_path_detail = '/content/drive/MyDrive/Dallas_County_25YR_Data/DCAD2025_CURRENT/RES_DETAIL.CSV'

#cols_needed_appr = ['ACCOUNT_NUM', 'LAND_VAL', 'TOT_VAL']
#cols_needed_info = ['ACCOUNT_NUM', 'APPRAISAL_YR', 'STREET_NUM', 'STREET_HALF_NUM', 'FULL_STREET_NAME', 'PROPERTY_ZIPCODE']
#cols_needed_detail = ['ACCOUNT_NUM', 'YR_BUILT', 'TOT_MAIN_SF', 'POOL_IND']

#df_appr = pd.read_csv(file_path_appr, usecols=cols_needed_appr, low_memory=False)
#df_info = pd.read_csv(file_path_info, usecols=cols_needed_info, low_memory=False)
#df_detail = pd.read_csv(file_path_detail, usecols=cols_needed_detail, low_memory=False)

#df_merged = df_appr.merge(df_info, on='ACCOUNT_NUM', how='left')
#df_merged = df_merged.merge(df_detail, on='ACCOUNT_NUM', how='left')

#df_merged.to_csv('/content/drive/MyDrive/Dallas_County_25YR_Data/DCAD2025_CURRENT/DCAD_Joined_2025.csv', index=False)

In [17]:
df_2020 = pd.read_csv('/content/drive/MyDrive/Dallas_County_25YR_Data/DCAD2020_CURRENT/DCAD_Joined_2020.csv')
df_2021 = pd.read_csv('/content/drive/MyDrive/Dallas_County_25YR_Data/DCAD2021_CURRENT/DCAD_Joined_2021.csv')
df_2022 = pd.read_csv('/content/drive/MyDrive/Dallas_County_25YR_Data/DCAD2022_CURRENT/DCAD_Joined_2022.csv')
df_2023 = pd.read_csv('/content/drive/MyDrive/Dallas_County_25YR_Data/DCAD2023_CURRENT/DCAD_Joined_2023.csv')
df_2024 = pd.read_csv('/content/drive/MyDrive/Dallas_County_25YR_Data/DCAD2024_CURRENT/DCAD_Joined_2024.csv')

df_combined = pd.concat([df_2020, df_2021, df_2022, df_2023, df_2024], ignore_index=True)

df_combined.info()

/tmp/ipykernel_843/539556797.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2020 = pd.read_csv('/content/drive/MyDrive/Dallas_County_25YR_Data/DCAD2020_CURRENT/DCAD_Joined_2020.csv')
/tmp/ipykernel_843/539556797.py:2: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2021 = pd.read_csv('/content/drive/MyDrive/Dallas_County_25YR_Data/DCAD2021_CURRENT/DCAD_Joined_2021.csv')
/tmp/ipykernel_843/539556797.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2022 = pd.read_csv('/content/drive/MyDrive/Dallas_County_25YR_Data/DCAD2022_CURRENT/DCAD_Joined_2022.csv')
/tmp/ipykernel_843/539556797.py:4: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2023 = pd.read_csv('/content/drive/MyDrive/Dallas_County_25YR_Data/DCAD2023_CURRENT/DCAD_Joined_2023.csv')
/tmp/ipykernel_843/539556797.py:5: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2024 = pd.read_csv('/content/drive/MyDrive/Dallas_County_25YR_Data/DCAD2024_CURRENT/DCAD_Joined_2024.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4245915 entries, 0 to 4245914
Data columns (total 11 columns):
 #   Column            Dtype
---  ------            -----
 0   ACCOUNT_NUM       object
 1   LAND_VAL          float64
 2   TOT_VAL           float64
 3   APPRAISAL_YR      int64
 4   STREET_NUM        float64
 5   STREET_HALF_NUM   object
 6   FULL_STREET_NAME  object
 7   PROPERTY_ZIPCODE  object
 8   YR_BUILT          float64
 9   TOT_MAIN_SF       float64
 10  POOL_IND          object
dtypes: float64(5), int64(1), object(5)
memory usage: 356.3+ MB

In [18]:
#To check zipcode columns for errors

df_combined[df_combined['PROPERTY_ZIPCODE'].isna()]

,ACCOUNT_NUM,LAND_VAL,TOT_VAL,APPRAISAL_YR,STREET_NUM,STREET_HALF_NUM,FULL_STREET_NAME,PROPERTY_ZIPCODE,YR_BUILT,TOT_MAIN_SF,POOL_IND
194,18DFW0000000MR800,10.0,10.0,2020,0.0,NaN,MINERAL RIGHTS,NaN,NaN,NaN,NaN
195,18DFW000000MR5400,10.0,10.0,2020,0.0,NaN,MINERAL RIGHTS,NaN,NaN,NaN,NaN
196,18DFW00000MR15030,10.0,10.0,2020,0.0,NaN,MINERAL RIGHTS,NaN,NaN,NaN,NaN
197,18DFW00000MR15035,10.0,10.0,2020,0.0,NaN,MINERAL RIGHTS,NaN,NaN,NaN,NaN
198,18DFW00000MR16092,10.0,10.0,2020,0.0,NaN,MINERAL RIGHTS,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3963953,99161027240000000,0.0,21870.0,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4012131,99250521200000000,0.0,3163090.0,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4059196,99L24632100000000,0.0,1570.0,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4066059,99L24627900000000,0.0,520.0,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4225558,99110425600000000,0.0,2390.0,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
#To drop rows with null values and convert the zipcode column to numeric

df_combined['PROPERTY_ZIPCODE'] = pd.to_numeric(
    df_combined['PROPERTY_ZIPCODE'], errors="coerce"
)

df_combined = df_combined.dropna(subset=['PROPERTY_ZIPCODE'])

df_combined['PROPERTY_ZIPCODE'] = df_combined['PROPERTY_ZIPCODE'].astype('int64')

In [21]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4064212 entries, 0 to 4245914
Data columns (total 11 columns):
 #   Column            Dtype
---  ------            -----
 0   ACCOUNT_NUM       object
 1   LAND_VAL          float64
 2   TOT_VAL           float64
 3   APPRAISAL_YR      int64
 4   STREET_NUM        float64
 5   STREET_HALF_NUM   object
 6   FULL_STREET_NAME  object
 7   PROPERTY_ZIPCODE  int64
 8   YR_BUILT          float64
 9   TOT_MAIN_SF       float64
 10  POOL_IND          object
dtypes: float64(5), int64(2), object(4)
memory usage: 372.1+ MB

In [22]:
#To change the POOL_IND datatype from object to boolean

df_combined['POOL_IND'] = df_combined['POOL_IND'].astype(bool)

In [23]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4064212 entries, 0 to 4245914
Data columns (total 11 columns):
 #   Column            Dtype
---  ------            -----
 0   ACCOUNT_NUM       object
 1   LAND_VAL          float64
 2   TOT_VAL           float64
 3   APPRAISAL_YR      int64
 4   STREET_NUM        float64
 5   STREET_HALF_NUM   object
 6   FULL_STREET_NAME  object
 7   PROPERTY_ZIPCODE  int64
 8   YR_BUILT          float64
 9   TOT_MAIN_SF       float64
 10  POOL_IND          bool
dtypes: bool(1), float64(5), int64(2), object(3)
memory usage: 345.0+ MB

In [24]:
df_combined.head(15)

,ACCOUNT_NUM,LAND_VAL,TOT_VAL,APPRAISAL_YR,STREET_NUM,STREET_HALF_NUM,FULL_STREET_NAME,PROPERTY_ZIPCODE,YR_BUILT,TOT_MAIN_SF,POOL_IND
0,00000557224000000,20000.0,76130.0,2020,7737.0,NaN,GAYGLEN DR,752176782,1959.0,1266.0,True
1,00000557251000000,20000.0,83810.0,2020,7719.0,NaN,OLUSTA DR,752176768,1959.0,986.0,True
2,00000557431000000,20000.0,87910.0,2020,8006.0,NaN,OLUSTA DR,752176758,1956.0,1182.0,True
3,26311500020120000,40000.0,128580.0,2020,1602.0,NaN,LEWIS DR,750414228,1959.0,1092.0,True
4,26312500050010100,45000.0,271480.0,2020,4101.0,NaN,NIAGARA ST,750415432,1975.0,2336.0,True
5,26318550040170000,3700.0,3700.0,2020,17.0,NaN,ARGYLL PL,75043,0.0,0.0,True
6,26318550070150000,32000.0,238660.0,2020,5801.0,NaN,STEPHEN CT,750436689,2006.0,1990.0,True
7,26318550080050000,32000.0,214240.0,2020,5817.0,NaN,MACGREGOR DR,750436686,2005.0,1893.0,True
8,26320500020140000,35000.0,190640.0,2020,313.0,NaN,JOYCE DR,750407868,1952.0,1324.0,True
9,26320500030110000,35000.0,173190.0,2020,301.0,NaN,FREEMAN DR,750407841,1950.0,1849.0,True
10,26322500000290000,35000.0,123230.0,2020,124.0,NaN,W AVE F,750407132,1949.0,1048.0,True
11,26322500000340000,35000.0,127180.0,2020,141.0,NaN,W AVE G,750407139,1949.0,1078.0,True
12,26322500000480000,35000.0,163650.0,2020,112.0,NaN,W AVE G,750407140,1949.0,1266.0,True
13,26323520010010000,95580.0,276170.0,2020,114.0,NaN,N 3RD ST,75040,NaN,NaN,True
14,24201500030090000,80000.0,170000.0,2020,2952.0,NaN,MARK TWAIN DR,752342130,1957.0,1344.0,True

In [26]:
#To drop all rows where the YR_BUILT column has null or zero values

df_combined = df_combined.dropna(subset=['YR_BUILT'])

df_combined = df_combined[df_combined['YR_BUILT'] != 0]

df_combined.head(15)

,ACCOUNT_NUM,LAND_VAL,TOT_VAL,APPRAISAL_YR,STREET_NUM,STREET_HALF_NUM,FULL_STREET_NAME,PROPERTY_ZIPCODE,YR_BUILT,TOT_MAIN_SF,POOL_IND
0,00000557224000000,20000.0,76130.0,2020,7737.0,NaN,GAYGLEN DR,752176782,1959.0,1266.0,True
1,00000557251000000,20000.0,83810.0,2020,7719.0,NaN,OLUSTA DR,752176768,1959.0,986.0,True
2,00000557431000000,20000.0,87910.0,2020,8006.0,NaN,OLUSTA DR,752176758,1956.0,1182.0,True
3,26311500020120000,40000.0,128580.0,2020,1602.0,NaN,LEWIS DR,750414228,1959.0,1092.0,True
4,26312500050010100,45000.0,271480.0,2020,4101.0,NaN,NIAGARA ST,750415432,1975.0,2336.0,True
6,26318550070150000,32000.0,238660.0,2020,5801.0,NaN,STEPHEN CT,750436689,2006.0,1990.0,True
7,26318550080050000,32000.0,214240.0,2020,5817.0,NaN,MACGREGOR DR,750436686,2005.0,1893.0,True
8,26320500020140000,35000.0,190640.0,2020,313.0,NaN,JOYCE DR,750407868,1952.0,1324.0,True
9,26320500030110000,35000.0,173190.0,2020,301.0,NaN,FREEMAN DR,750407841,1950.0,1849.0,True
10,26322500000290000,35000.0,123230.0,2020,124.0,NaN,W AVE F,750407132,1949.0,1048.0,True
11,26322500000340000,35000.0,127180.0,2020,141.0,NaN,W AVE G,750407139,1949.0,1078.0,True
12,26322500000480000,35000.0,163650.0,2020,112.0,NaN,W AVE G,750407140,1949.0,1266.0,True
14,24201500030090000,80000.0,170000.0,2020,2952.0,NaN,MARK TWAIN DR,752342130,1957.0,1344.0,True
15,24202500020040000,50000.0,186880.0,2020,13919.0,NaN,SUNDOWN TRL,752343540,1957.0,1092.0,True
16,24203500040230000,100000.0,226110.0,2020,13905.0,NaN,HEARTSIDE PL,752343627,1958.0,1384.0,True

In [27]:
df_combined.to_parquet('/content/drive/MyDrive/Dallas_County_25YR_Data/DCAD_20_to_24.parquet')